# fly.toml file generated for almanara-covid on 2022-12-05T09:05:26-03:00

app = "almanara-covid"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  HOST = "127.0.0.1"
  CACHE_VIEWS="false"
  APP_NAME="MORBI"
  APP_URL="http://${HOST}:${PORT}"
  HASH_DRIVER="bcrypt"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
